import { Badge } from "@openai/apps-sdk-ui/components/Badge";
import { Input } from "@openai/apps-sdk-ui/components/Input";
import { Select } from "@openai/apps-sdk-ui/components/Select";
import { Switch } from "@openai/apps-sdk-ui/components/Switch";
import type { WalletCard, WorkflowGraph } from "../../lib/desktop";
import { StateLine } from "../shared";

type Node = WorkflowGraph["nodes"][number];
export type SelectedWorkflowItem = { kind: "node"; node: Node; wallet: WalletCard[]; onUpdate: (id: string, patch: Partial<Node>) => void } | { kind: "edge"; edge: WorkflowGraph["edges"][number] } | null;

export function WorkflowInspector({ selected }: { selected: SelectedWorkflowItem }) {
  if (!selected) return <><StateLine label="选择" value="未选择节点" /><div className="next-step"><strong>画布操作</strong><p>选择节点或连接后在这里查看属性。拖动类型化端口可以创建安全连接。</p></div></>;
  if (selected.kind === "edge") return <><Badge color="info" variant="soft">类型化连接</Badge><StateLine label="ID" value={selected.edge.id} /><StateLine label="来源" value={`${selected.edge.from.node}.${selected.edge.from.port}`} /><StateLine label="目标" value={`${selected.edge.to.node}.${selected.edge.to.port}`} /><div className="next-step"><strong>连接约束</strong><p>连接类型由两端端口决定。删除连接会形成未保存草稿，并在保存时由 Rust 再次校验。</p></div></>;
  const { node, wallet, onUpdate } = selected;
  const config = node.config ?? {};
  const patchConfig = (patch: Record<string, unknown>) => onUpdate(node.id, { config: { ...config, ...patch } });
  return <div className="workflow-inspector"><Badge color={node.enabled ? "success" : "secondary"} variant="soft">{kindLabel(node.kind)}</Badge><label className="field-label">节点名称<Input value={node.name} onChange={(event) => onUpdate(node.id, { name: event.target.value })} /></label><StateLine label="节点 ID" value={node.id} /><StateLine label="端口" value={`${node.inputs.length} 入 / ${node.outputs.length} 出`} />{node.kind === "adapter" ? <AdapterFields wallet={wallet} config={config} onChange={patchConfig} /> : null}{node.kind === "router" ? <><NumberField label="超时（毫秒）" value={numberValue(config.timeout_ms, 30000)} min={1000} onChange={(timeout_ms) => patchConfig({ timeout_ms })} /><NumberField label="最大重试" value={numberValue(config.max_retries, 2)} min={0} max={10} onChange={(max_retries) => patchConfig({ max_retries })} /><StateLine label="策略" value="按优先级故障切换" /></> : null}{node.kind === "probe" ? <><Switch checked={config.safe_only !== false} label="仅无副作用探测" onCheckedChange={(safe_only) => patchConfig({ safe_only })} /><NumberField label="探测间隔（秒）" value={numberValue(config.interval_seconds, 300)} min={30} onChange={(interval_seconds) => patchConfig({ interval_seconds })} /><NumberField label="失败阈值" value={numberValue(config.failure_threshold, 3)} min={1} max={20} onChange={(failure_threshold) => patchConfig({ failure_threshold })} /></> : null}{node.kind === "guard" ? <><NumberField label="预算预警（%）" value={numberValue(config.budget_warning_percent, 80)} min={1} max={100} onChange={(budget_warning_percent) => patchConfig({ budget_warning_percent })} /><NumberField label="每分钟请求上限" value={numberValue(config.rate_limit_per_minute, 60)} min={1} onChange={(rate_limit_per_minute) => patchConfig({ rate_limit_per_minute })} /></> : null}{node.kind === "transform" ? <label className="field-label">转换预设<Select value={stringValue(config.preset, "openai_compatible")} options={[{ value: "openai_compatible", label: "OpenAI-compatible 规范化" }, { value: "model_alias", label: "模型别名映射" }, { value: "response_normalize", label: "响应结构规范化" }]} onChange={(option) => patchConfig({ preset: option.value })} /></label> : null}{node.kind === "group" ? <Switch checked={Boolean(config.collapsed)} label="折叠节点组" onCheckedChange={(collapsed) => patchConfig({ collapsed })} /> : null}{node.kind === "publisher" ? <div className="next-step"><strong>Canvas 总输出器</strong><p>总输出器不可停用或删除。Alias、公开模型和 Token 请在“出口”页配置。</p></div> : <Switch checked={node.enabled} label={node.enabled ? "已启用" : "已停用"} onCheckedChange={(enabled) => onUpdate(node.id, { enabled })} />}<div className="next-step"><strong>Secret 安全边界</strong><p>节点只保存钱包资产 ID 和安全配置。密钥值不会进入图、UI State 或日志。</p></div></div>;
}

function AdapterFields({ wallet, config, onChange }: { wallet: WalletCard[]; config: Record<string, unknown>; onChange: (patch: Record<string, unknown>) => void }) {
  const assets = wallet.filter((item) => item.source === "asset" && item.providerInstanceId);
  const assetId = stringValue(config.asset_id, "");
  const selected = assets.find((item) => item.id === assetId);
  return <><label className="field-label">钱包资产<Select value={assetId} options={assets.map((asset) => ({ value: asset.id, label: asset.name }))} onChange={(option) => { const asset = assets.find((item) => item.id === option.value); onChange({ asset_id: option.value, provider_instance_id: asset?.providerInstanceId ?? null, secret_ready: asset?.configured ?? false }); }} /></label><label className="field-label">公开模型<Input value={stringValue(config.public_model, "default")} onChange={(event) => onChange({ public_model: event.target.value })} /></label><label className="field-label">上游模型<Input value={stringValue(config.upstream_model, "default")} onChange={(event) => onChange({ upstream_model: event.target.value })} /></label><Badge color={selected?.configured && selected.enabled ? "success" : "warning"} variant="soft">{selected?.configured ? selected.enabled ? "资产已就绪" : "资产已停用" : "缺少 Key"}</Badge></>;
}
function NumberField({ label, value, min, max, onChange }: { label: string; value: number; min?: number; max?: number; onChange: (value: number) => void }) { return <label className="field-label">{label}<Input type="number" value={String(value)} min={min} max={max} onChange={(event) => onChange(Number(event.target.value))} /></label>; }
function numberValue(value: unknown, fallback: number) { return typeof value === "number" && Number.isFinite(value) ? value : fallback; }
function stringValue(value: unknown, fallback: string) { return typeof value === "string" ? value : fallback; }
function kindLabel(kind: Node["kind"]) { return ({ adapter: "钱包资产", probe: "健康探测", transform: "协议转换", router: "路由器", guard: "安全规则", publisher: "总输出器", group: "节点组" })[kind]; }
