import { Button } from "@openai/apps-sdk-ui/components/Button";
import { SidebarCollapseLeft, SidebarOpenLeft } from "@openai/apps-sdk-ui/components/Icon";
import { Tooltip } from "@openai/apps-sdk-ui/components/Tooltip";
import type { ProjectTree as Model, PublisherSnapshot, WorkspaceUiState } from "../../lib/desktop";
import { navigation, type AppPage } from "../navigation";
import { ProjectTree } from "./ProjectTree";

export function LeftSidebar({ page, tree, publishers, uiState, collapsed, onNavigate, onOpenCanvas, onTree, onUiState, onToggle }: { page: AppPage | null; tree: Model; publishers: PublisherSnapshot[]; uiState: WorkspaceUiState; collapsed: boolean; onNavigate: (page: AppPage) => void; onOpenCanvas: (projectId: string, canvasId: string) => void; onTree: (tree: Model) => void; onUiState: (state: WorkspaceUiState) => void; onToggle: () => void }) {
  const renderItem = (item: (typeof navigation)[number]) => { const Icon = item.icon; const button = <button className={`nav-item ${page === item.id ? "selected" : ""}`} aria-label={collapsed ? `${item.label}：${item.hint}` : undefined} aria-current={page === item.id ? "page" : undefined} onClick={() => onNavigate(item.id)}><Icon className="size-4" aria-hidden="true" />{collapsed ? null : <span>{item.label}</span>}</button>; return collapsed ? <Tooltip key={item.id} content={`${item.label} · ${item.hint}`} side="right">{button}</Tooltip> : <span key={item.id}>{button}</span>; };
  const nav = (group: "global" | "support") => <section className={`nav-group nav-${group}`}>{!collapsed ? <p>{group === "global" ? "API 管理" : "运行与设置"}</p> : null}{navigation.filter((item) => item.group === group).map(renderItem)}</section>;
  const home = navigation.find((item) => item.group === "home")!;
  const showProjects = page === "compositions" || page === null;
  return <nav className={`sidebar ${collapsed ? "collapsed" : ""}`} aria-label="主导航"><div className="sidebar-heading"><span>{collapsed ? "" : "API ARRAY"}</span><Tooltip content={collapsed ? "展开侧栏" : "折叠侧栏"}><Button color="secondary" variant="ghost" size="sm" uniform aria-label={collapsed ? "展开侧栏" : "折叠侧栏"} onClick={onToggle}>{collapsed ? <SidebarOpenLeft /> : <SidebarCollapseLeft />}</Button></Tooltip></div><section className="nav-group nav-home">{renderItem(home)}</section>{nav("global")}{!collapsed && showProjects ? <ProjectTree tree={tree} publishers={publishers} selectedProjectId={uiState.selectedProjectId} selectedCanvasId={uiState.selectedCanvasId} expandedProjects={uiState.expandedProjectIds} expandedFolders={uiState.expandedFolderIds} onTree={onTree} onOpenCanvas={onOpenCanvas} onToggleProject={(id) => onUiState({ ...uiState, expandedProjectIds: toggle(uiState.expandedProjectIds, id) })} onToggleFolder={(id) => onUiState({ ...uiState, expandedFolderIds: toggle(uiState.expandedFolderIds, id) })} /> : null}<div className="sidebar-spacer" />{nav("support")}</nav>;
}
function toggle(items: string[], id: string) { return items.includes(id) ? items.filter((item) => item !== id) : [...items, id]; }
