import { Button } from "@openai/apps-sdk-ui/components/Button";
import { Menu } from "@openai/apps-sdk-ui/components/Menu";
import { Tooltip } from "@openai/apps-sdk-ui/components/Tooltip";
import { ArrowRotateCcw, CloseBold, ColorTheme, Expand, MinimizeDown, Moon, MoonSunSystem, SidebarOpenRight, Sun } from "@openai/apps-sdk-ui/components/Icon";
import type { AppIcon } from "../navigation";
import type { ThemePreference } from "../../lib/desktop";

export function UnifiedTopBar({ workspaceName, pageLabel, pageIcon: PageIcon, theme, onTheme, onRefresh, onOpenInspector }: { workspaceName: string; pageLabel: string; pageIcon: AppIcon; theme: ThemePreference; onTheme: (theme: ThemePreference) => void; onRefresh: () => void; onOpenInspector: () => void }) {
  const callWindow = async (action: "minimize" | "toggleMaximize" | "close") => { const { getCurrentWindow } = await import("@tauri-apps/api/window"); await getCurrentWindow()[action](); };
  return <header className="unified-topbar"><div className="topbar-drag" data-tauri-drag-region><strong className="topbar-brand" data-tauri-drag-region>API ARRAY</strong><span className="topbar-divider" /><span className="topbar-workspace" data-tauri-drag-region>{workspaceName}</span><span className="topbar-crumb"><PageIcon aria-hidden="true" />{pageLabel}</span></div><div className="topbar-actions"><Menu><Menu.Trigger><Tooltip content="切换主题"><Button color="secondary" variant="ghost" size="sm" uniform aria-label="切换主题"><ColorTheme /></Button></Tooltip></Menu.Trigger><Menu.Content align="end" side="bottom" minWidth={160}><Menu.RadioGroup value={theme} onChange={onTheme}><Menu.RadioItem value="system"><MoonSunSystem />跟随系统</Menu.RadioItem><Menu.RadioItem value="light"><Sun />亮色</Menu.RadioItem><Menu.RadioItem value="dark"><Moon />暗色</Menu.RadioItem></Menu.RadioGroup></Menu.Content></Menu><Tooltip content="刷新状态"><Button color="secondary" variant="ghost" size="sm" uniform aria-label="刷新状态" onClick={onRefresh}><ArrowRotateCcw /></Button></Tooltip><Tooltip content="打开属性栏"><Button color="secondary" variant="ghost" size="sm" uniform aria-label="打开属性栏" onClick={onOpenInspector}><SidebarOpenRight /></Button></Tooltip><span className="window-controls"><Button color="secondary" variant="ghost" size="sm" uniform aria-label="最小化" onClick={() => void callWindow("minimize")}><MinimizeDown /></Button><Button color="secondary" variant="ghost" size="sm" uniform aria-label="最大化或恢复" onClick={() => void callWindow("toggleMaximize")}><Expand /></Button><Button color="danger" variant="ghost" size="sm" uniform aria-label="关闭到托盘" onClick={() => void callWindow("close")}><CloseBold /></Button></span></div></header>;
}
