"use client";
import { Badge } from "@openai/apps-sdk-ui/components/Badge";
import { Button } from "@openai/apps-sdk-ui/components/Button";
import { Input } from "@openai/apps-sdk-ui/components/Input";
import { Select } from "@openai/apps-sdk-ui/components/Select";
import { SegmentedControl } from "@openai/apps-sdk-ui/components/SegmentedControl";
import { Switch } from "@openai/apps-sdk-ui/components/Switch";
import { Textarea } from "@openai/apps-sdk-ui/components/Textarea";
import { ArrowRotateCcw, Bell, CheckCircle, Code, FileDocument, History, Settings as SettingsIcon } from "@openai/apps-sdk-ui/components/Icon";
import { useEffect, useState } from "react";
import { backupWorkspace, compactWorkspace, exportWorkspace, getAuditRecords, getCanvasLiveDocument, getWorkspaceLocations, getWorkspaceStorageStatus, importWorkspace, openWorkspaceAt, relocateWorkspace, saveLiveDocumentMarkdown, verifyWorkspace, type DesktopSnapshot, type ExecutionTrace, type LiveDocument, type PublisherSnapshot, type TemplateLanguage, type WorkspaceLocation, type WorkspaceStorageStatus, type WorkspaceUiState } from "../../lib/desktop";
import { LiveDocumentation } from "../documentation/LiveDocumentation";
import { EmptyPage, formatTimestamp, readError } from "../shared";

export function NotificationsPage({ notifications }: { notifications: NonNullable<DesktopSnapshot["control"]>["notifications"] }) { if (!notifications.length) return <EmptyPage page="暂无通知" hint="重复错误会被聚合，避免循环刷屏。" icon={Bell} />; return <div className="notification-list">{notifications.map((notice, index) => <article key={notice.id ?? index}><div className="notification-heading"><Bell /><Badge color="info" variant="soft">本地事件</Badge></div><strong>{notice.message}</strong><small>{formatTimestamp(notice.createdAt)}</small></article>)}</div>; }

export function RunsPage() {
  const [records, setRecords] = useState<ExecutionTrace[]>([]); const [message, setMessage] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const refresh = async () => { setLoading(true); try { setRecords(await getAuditRecords()); setMessage(null); } catch (reason) { setMessage(readError(reason)); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, []);
  if (loading) return <EmptyPage page="正在读取运行记录" hint="审计只保存脱敏元数据。" icon={History} />;
  return <section className="runs-view"><div className="section-heading"><div><p className="eyebrow">Local Audit</p><h2>运行记录</h2></div><Button color="secondary" variant="soft" onClick={() => void refresh()}><ArrowRotateCcw />刷新</Button></div>{message ? <p className="error-message" role="alert">{message}</p> : null}{records.length ? <div className="run-list">{records.map((record) => <article className="run-card" key={record.correlation_id}><div className="run-heading"><div><strong>{record.publisher_id}</strong><small>{record.public_model} · {formatTimestamp(record.started_at_unix_ms)}</small></div><Badge color={record.result === "success" ? "success" : "danger"} variant="soft">{record.result}</Badge></div><div className="run-metrics"><span>{record.total_latency_ms} ms</span><span>{record.retry_count} 次重试</span><span>{record.failover_count} 次切换</span><span>{record.streaming ? "流式" : "非流式"}</span></div></article>)}</div> : <EmptyPage page="暂无运行记录" hint="本地入口收到请求后会在这里显示审计摘要。" icon={History} />}</section>;
}

export function TemplatesPage({ publishers }: { publishers: PublisherSnapshot[] }) {
  const [selected, setSelected] = useState(""); const [document, setDocument] = useState<LiveDocument | null>(null); const [language, setLanguage] = useState<TemplateLanguage>("curl"); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { setSelected(publishers[0]?.id ?? ""); }, [publishers]);
  useEffect(() => { if (!selected) { setDocument(null); return; } setDocument(null); void getCanvasLiveDocument(selected, language).then(setDocument).catch((reason) => setMessage(readError(reason))); }, [selected, language]);
  if (!publishers.length) return <EmptyPage page="暂无可用模板" hint="创建 Publisher 后生成活文档。" icon={Code} />;
  return <section className="templates-view"><div className="section-heading"><div><p className="eyebrow">Live Documentation</p><h2>活文档与调用模板</h2></div><Badge color="success" variant="soft">实时生成</Badge></div>{message ? <p className="error-message" role="alert">{message}</p> : null}<label className="field-label">Publisher<Select options={publishers.map((publisher) => ({ value: publisher.id, label: publisher.id }))} value={selected} onChange={(option) => setSelected(option.value)} /></label><LiveDocumentation document={document} language={language} loading={Boolean(selected)} onLanguage={setLanguage} onSave={() => saveLiveDocumentMarkdown("canvas", selected, language, `${selected}-${language}`)} /></section>;
}

export function SettingsPage({ onSnapshot, uiState, onUiState }: { onSnapshot: (snapshot: DesktopSnapshot) => void; uiState: WorkspaceUiState; onUiState: (state: WorkspaceUiState) => void }) {
  const [enabled, setEnabled] = useState<boolean | null>(null); const [busy, setBusy] = useState(false); const [workspaceJson, setWorkspaceJson] = useState(""); const [message, setMessage] = useState<string | null>(null); const [storage, setStorage] = useState<WorkspaceStorageStatus | null>(null); const [locations, setLocations] = useState<WorkspaceLocation[]>([]); const [workspacePath, setWorkspacePath] = useState("");
  const refreshStorage = async () => { const [status, known] = await Promise.all([getWorkspaceStorageStatus(), getWorkspaceLocations()]); setStorage(status); setLocations(known); };
  useEffect(() => { void import("@tauri-apps/plugin-autostart").then(({ isEnabled }) => isEnabled().then(setEnabled)).catch(() => setEnabled(false)); void refreshStorage().catch((reason) => setMessage(readError(reason))); }, []);
  const toggle = async (next: boolean) => { setBusy(true); try { const plugin = await import("@tauri-apps/plugin-autostart"); if (next) await plugin.enable(); else await plugin.disable(); setEnabled(next); } finally { setBusy(false); } };
  const storageAction = async (action: "verify" | "backup" | "compact") => { setBusy(true); try { if (action === "backup") { const result = await backupWorkspace(); setMessage(`备份完成：${result.path}`); } else { setStorage(await (action === "verify" ? verifyWorkspace() : compactWorkspace())); setMessage(action === "verify" ? "数据库完整性检查通过。" : "数据库压缩完成。"); } } catch (reason) { setMessage(readError(reason)); } finally { setBusy(false); } };
  const browse = async () => { const { open } = await import("@tauri-apps/plugin-dialog"); const selected = await open({ directory: true, multiple: false, title: "选择 API ARRAY 工作区目录" }); if (typeof selected === "string") setWorkspacePath(selected); };
  const switchWorkspace = async (relocate: boolean) => { if (!workspacePath.trim()) return; setBusy(true); try { onSnapshot(await (relocate ? relocateWorkspace(workspacePath) : openWorkspaceAt(workspacePath))); setMessage(relocate ? "工作区已复制、验证并切换；原目录仍保留。" : "工作区已重新连接。"); window.location.reload(); } catch (reason) { setMessage(readError(reason)); } finally { setBusy(false); } };
  const exportCurrent = async () => { setBusy(true); try { const json = await exportWorkspace(); setWorkspaceJson(json); await navigator.clipboard.writeText(json); setMessage("脱敏交换包已复制，不包含 Secret 明文。"); } catch (reason) { setMessage(readError(reason)); } finally { setBusy(false); } };
  const importCurrent = async () => { if (!workspaceJson.trim()) return; setBusy(true); try { onSnapshot(await importWorkspace(workspaceJson)); setMessage("脱敏交换包已导入。"); } catch (reason) { setMessage(readError(reason)); } finally { setBusy(false); } };
  return <div className="settings-view">
    {message ? <p className="success-message" role="status">{message}</p> : null}
    <section className="appearance-card"><div><p className="eyebrow">Appearance</p><h2>外观</h2><p>跟随 Windows 或使用独立主题。</p></div><SegmentedControl value={uiState.themePreference} onChange={(themePreference) => onUiState({ ...uiState, themePreference })} aria-label="主题偏好" block><SegmentedControl.Option value="system">系统</SegmentedControl.Option><SegmentedControl.Option value="light">亮色</SegmentedControl.Option><SegmentedControl.Option value="dark">暗色</SegmentedControl.Option></SegmentedControl></section>
    <section className="setting-card"><div><div className="setting-title"><SettingsIcon /><h2>开机启动</h2></div><p>仅保存为此设备偏好。</p></div><Switch checked={enabled ?? false} disabled={busy || enabled === null} label={enabled ? "已开启" : "已关闭"} onCheckedChange={(next) => void toggle(next)} /></section>
    <section className="workspace-storage-card"><div className="section-heading"><div><p className="eyebrow">SQLite Workspace</p><h2>工作区与存储</h2><p>配置和脱敏审计保存在 SQLite；Key 与 Token 仍在 Windows Credential Manager。</p></div><Badge color={storage?.healthy ? "success" : "warning"} variant="soft">{storage?.healthy ? "数据库健康" : "等待检查"}</Badge></div><div className="storage-metrics"><span><strong>{storage?.revision ?? "—"}</strong>数据修订</span><span><strong>{storage ? `${(storage.database_bytes / 1024).toFixed(1)} KB` : "—"}</strong>数据库大小</span><span><strong>{storage?.integrity_message ?? "—"}</strong>完整性</span></div><div className="form-actions"><Button color="secondary" variant="soft" loading={busy} onClick={() => void storageAction("verify")}>检查</Button><Button color="secondary" variant="soft" loading={busy} onClick={() => void storageAction("backup")}>备份</Button><Button color="secondary" variant="ghost" loading={busy} onClick={() => void storageAction("compact")}>压缩</Button></div><label className="field-label">打开或迁移到目录<div className="path-picker"><Input value={workspacePath} onChange={(event) => setWorkspacePath(event.target.value)} /><Button color="secondary" variant="soft" onClick={() => void browse()}><FileDocument />浏览</Button></div></label><div className="form-actions"><Button color="secondary" variant="soft" disabled={!workspacePath} onClick={() => void switchWorkspace(false)}>重新连接</Button><Button color="primary" disabled={!workspacePath} onClick={() => void switchWorkspace(true)}>复制验证后迁移</Button></div><div className="known-workspaces"><strong>最近工作区</strong>{locations.map((location) => <button key={location.id} onClick={() => setWorkspacePath(location.root)}>{location.name}<small>{location.root}</small></button>)}</div></section>
    <section className="workspace-transfer"><div className="section-heading"><div><p className="eyebrow">Portable Export</p><h2>脱敏导入与导出</h2></div><Badge color="info" variant="soft">不是运行数据库</Badge></div><Textarea value={workspaceJson} onChange={(event) => setWorkspaceJson(event.target.value)} rows={10} placeholder="版本化脱敏交换包" /><div className="form-actions"><Button color="secondary" variant="soft" loading={busy} onClick={() => void exportCurrent()}><FileDocument />导出</Button><Button color="primary" loading={busy} disabled={!workspaceJson.trim()} onClick={() => void importCurrent()}><CheckCircle />导入</Button></div></section>
  </div>;
}
