"use client";

import { Badge } from "@openai/apps-sdk-ui/components/Badge";
import { Button } from "@openai/apps-sdk-ui/components/Button";
import { Input } from "@openai/apps-sdk-ui/components/Input";
import { Select } from "@openai/apps-sdk-ui/components/Select";
import { SegmentedControl } from "@openai/apps-sdk-ui/components/SegmentedControl";
import { ArrowRotateCcw, Branch, Code, History, Pause, Play, Plugin, Stop } from "@openai/apps-sdk-ui/components/Icon";
import { useCallback, useEffect, useMemo, useState } from "react";
import { createCanvasPublisher, getAuditRecords, getCanvasLiveDocument, getCanvasSnapshot, getWalletGallery, pauseCanvas, refreshCanvas, runCanvas, stopCanvas, validateCanvasRuntime, type CanvasSnapshot, type CanvasTab, type DesktopSnapshot, type ExecutionTrace, type LiveDocument, type TemplateLanguage, type WalletCard, type WorkspaceUiState } from "../../lib/desktop";
import { readError } from "../shared";
import { LiveDocumentation } from "../documentation/LiveDocumentation";
import { WorkflowCanvas } from "../workflow/WorkflowCanvas";
import type { SelectedWorkflowItem } from "../workflow/WorkflowInspector";

const tabs: Array<{ id: CanvasTab; label: string }> = [{ id: "overview", label: "概览" }, { id: "workflow", label: "编排" }, { id: "routes", label: "API 与路由" }, { id: "publisher", label: "出口" }, { id: "docs", label: "文档" }, { id: "runs", label: "运行记录" }];
type RuntimeValidationReport = Awaited<ReturnType<typeof validateCanvasRuntime>>;

export function CanvasWorkspace({ projectId, canvasId, tab, uiState, onTab, onUiState, onDesktopSnapshot, onWorkflowSelection, onChanged }: { projectId: string; canvasId: string; tab: CanvasTab; uiState: WorkspaceUiState; onTab: (tab: CanvasTab) => void; onUiState: (state: WorkspaceUiState) => void; onDesktopSnapshot: (snapshot: DesktopSnapshot) => void; onWorkflowSelection: (selection: SelectedWorkflowItem) => void; onChanged: () => void }) {
  const [snapshot, setSnapshot] = useState<CanvasSnapshot | null>(null); const [wallet, setWallet] = useState<WalletCard[]>([]); const [document, setDocument] = useState<LiveDocument | null>(null); const [records, setRecords] = useState<ExecutionTrace[]>([]); const [runtimeReport, setRuntimeReport] = useState<RuntimeValidationReport | null>(null); const [language, setLanguage] = useState<TemplateLanguage>("curl"); const [dialog, setDialog] = useState(false); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [publisherId, setPublisherId] = useState(`${canvasId}-api`); const [port, setPort] = useState("6188"); const [token, setToken] = useState("");
  const load = useCallback(async () => { try { const [next, assets, audits, report] = await Promise.all([getCanvasSnapshot(projectId, canvasId), getWalletGallery(), getAuditRecords(500), validateCanvasRuntime(projectId, canvasId).catch(() => null)]); setSnapshot(next); setWallet(assets); setRuntimeReport(report); setRecords(next.publisher ? audits.filter((record) => record.publisher_id === next.publisher?.id) : []); setError(null); } catch (reason) { setError(readError(reason)); } }, [canvasId, projectId]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!snapshot?.publisher) { setDocument(null); return; } setDocument(null); void getCanvasLiveDocument(snapshot.publisher.id, language).then(setDocument).catch((reason) => setError(readError(reason))); }, [snapshot?.publisher?.id, language]);
  const placed = useMemo(() => wallet.filter((asset) => snapshot?.assetIds.includes(asset.id)), [snapshot, wallet]);
  const lifecycle = snapshot?.publisher?.status ?? "draft"; const dirty = Boolean(snapshot && snapshot.canvas.draftRevision !== snapshot.canvas.appliedRevision);
  const execute = async (key: string, action: () => Promise<DesktopSnapshot | unknown>) => { setBusy(key); setError(null); try { const result = await action(); if (isDesktopSnapshot(result)) onDesktopSnapshot(result); await load(); onChanged(); } catch (reason) { setError(readError(reason)); } finally { setBusy(null); } };
  const start = async () => { if (!snapshot) return; try { const report = await validateCanvasRuntime(projectId, canvasId); setRuntimeReport(report); if (!report.valid || report.errors.length) { setError(report.errors.map((issue) => issue.message).join("；") || "编组方案运行语义校验失败。"); onTab("workflow"); return; } if (!snapshot.publisher) { setDialog(true); return; } await execute("run", () => runCanvas(projectId, canvasId)); } catch (reason) { setError(readError(reason)); onTab("workflow"); } };
  const publishAndRun = async () => { if (!token.trim()) return; setBusy("publish"); try { const next = await createCanvasPublisher({ projectId, canvasId, id: publisherId, name: publisherId, port: Number(port), token }); onDesktopSnapshot(next); setToken(""); setDialog(false); await runCanvas(projectId, canvasId).then(onDesktopSnapshot); await load(); onChanged(); } catch (reason) { setError(readError(reason)); } finally { setBusy(null); } };
  if (!snapshot) return <section className="canvas-workspace"><p className="muted">正在打开编组方案…</p>{error ? <p className="error-message" role="alert">{error}</p> : null}</section>;
  return <section className="canvas-workspace">
    <header className="canvas-workspace-header"><div><p className="eyebrow">{snapshot.projectName} / 编组方案</p><div className="canvas-title-line"><h1>{snapshot.canvas.name}</h1><Badge color={lifecycle === "running" ? "success" : lifecycle === "paused" ? "warning" : lifecycle === "failed" ? "danger" : "secondary"} variant="soft">{lifecycleLabel(lifecycle)}</Badge><Badge color={dirty ? "info" : "secondary"} variant="soft">{dirty ? `未应用草稿 r${snapshot.canvas.draftRevision}` : `已应用 r${snapshot.canvas.appliedRevision}`}</Badge></div></div><div className="canvas-runtime-actions"><Button color="success" size="sm" loading={busy === "run"} disabled={busy !== null} onClick={() => void start()}><Play />{dirty && snapshot.publisher ? "应用并运行" : "运行"}</Button><Button color="warning" variant="soft" size="sm" disabled={!snapshot.publisher || busy !== null} onClick={() => void execute("pause", () => pauseCanvas(projectId, canvasId))}><Pause />暂停</Button><Button color="danger" variant="soft" size="sm" disabled={!snapshot.publisher || busy !== null} onClick={() => void execute("stop", () => stopCanvas(projectId, canvasId))}><Stop />停止</Button><Button color="secondary" variant="ghost" size="sm" disabled={busy !== null} onClick={() => void execute("refresh", () => refreshCanvas(projectId, canvasId))}><ArrowRotateCcw />刷新体检</Button></div></header>
    {error ? <p className="error-message" role="alert">{error}</p> : null}
    {runtimeReport ? <RuntimeReportPanel report={runtimeReport} onOpenWorkflow={() => onTab("workflow")} /> : null}
    <SegmentedControl className="canvas-tabs" value={tab} onChange={(value) => onTab(value as CanvasTab)} size="sm" aria-label="编组方案工作台页面">{tabs.map((item) => <SegmentedControl.Option key={item.id} value={item.id}>{item.label}</SegmentedControl.Option>)}</SegmentedControl>
    <div className={`canvas-tab-content tab-${tab}`}>{tab === "overview" ? <Overview snapshot={snapshot} assets={placed} dirty={dirty} onTab={onTab} /> : null}{tab === "workflow" ? <WorkflowCanvas projectId={projectId} canvasId={canvasId} expectedDraftRevision={snapshot.canvas.draftRevision} wallet={wallet} uiState={uiState} onUiState={onUiState} publisherRunning={lifecycle === "running"} onSelection={onWorkflowSelection} onGraphChange={() => void load()} /> : null}{tab === "routes" ? <Routes assets={placed} /> : null}{tab === "publisher" ? <Publisher snapshot={snapshot} onCreate={() => setDialog(true)} /> : null}{tab === "docs" ? <Docs document={document} language={language} onLanguage={setLanguage} published={Boolean(snapshot.publisher)} /> : null}{tab === "runs" ? <Runs records={records} /> : null}</div>
    {dialog ? <div className="wallet-dialog" role="dialog" aria-modal="true" aria-label="配置编组方案本地出口"><div><Button className="dialog-close" color="secondary" variant="ghost" uniform aria-label="关闭" onClick={() => setDialog(false)}>×</Button><p className="eyebrow">COMPOSITION OUTPUT</p><h2>配置本地出口</h2><p>公开模型和上游路由完全来自 Composer。这里只配置本机入口与独立 Token。</p><label className="field-label">出口 ID<Input value={publisherId} onChange={(event) => setPublisherId(event.target.value)} /></label><label className="field-label">端口<Input type="number" min="1024" max="65535" value={port} onChange={(event) => setPort(event.target.value)} /></label><label className="field-label">本地访问 Token<Input type="password" value={token} onChange={(event) => setToken(event.target.value)} autoComplete="new-password" /></label><Button color="primary" block loading={busy === "publish"} disabled={!token.trim()} onClick={() => void publishAndRun()}>发布并运行</Button></div></div> : null}
  </section>;
}

function Overview({ snapshot, assets, dirty, onTab }: { snapshot: CanvasSnapshot; assets: WalletCard[]; dirty: boolean; onTab: (tab: CanvasTab) => void }) { return <div className="canvas-overview-grid"><article><Branch /><span>Canonical 编组</span><strong>{snapshot.canvas.graph.nodes.length} 个节点</strong><small>{dirty ? "有待应用修改" : "与运行版本一致"}</small><Button color="secondary" variant="ghost" size="sm" onClick={() => onTab("workflow")}>打开编排</Button></article><article><Plugin /><span>本地出口</span><strong>{snapshot.publisher?.baseUrl ?? "尚未发布"}</strong><small>{snapshot.publisher?.publicModels.join("、") || "模型由 Composer 生成"}</small><Button color="secondary" variant="ghost" size="sm" onClick={() => onTab("publisher")}>查看出口</Button></article><article><Code /><span>Provider 候选</span><strong>{assets.length} 个上游</strong><small>{snapshot.missingSecretCount ? `${snapshot.missingSecretCount} 个 Secret 缺失` : "凭据状态正常"}</small><Button color="secondary" variant="ghost" size="sm" onClick={() => onTab("routes")}>查看路由</Button></article></div>; }
function Routes({ assets }: { assets: WalletCard[] }) { return <div className="canvas-list-page"><div className="section-heading"><div><p className="eyebrow">CANONICAL CANDIDATES</p><h2>API 与路由</h2></div><Badge color="info" variant="soft">{assets.length} 个候选</Badge></div>{assets.length ? assets.map((asset, index) => <article className="route-asset" key={asset.id}><span>{index === 0 ? "主" : `备 ${index}`}</span><div><strong>{asset.name}</strong><small>{asset.configured && asset.enabled ? "可由 Composer 调度" : "当前不可运行"}</small></div></article>) : <p className="empty-state">请在编排页从 API 钱包添加 Provider。</p>}</div>; }
function Publisher({ snapshot, onCreate }: { snapshot: CanvasSnapshot; onCreate: () => void }) { return <div className="canvas-list-page"><div className="section-heading"><div><p className="eyebrow">CANVAS OUTPUT</p><h2>本地出口</h2></div>{snapshot.publisher ? <Badge color="success" variant="soft">已绑定</Badge> : <Button color="primary" onClick={onCreate}>配置出口</Button>}</div>{snapshot.publisher ? <article className="canvas-publisher-card"><Plugin /><div><strong>{snapshot.publisher.id}</strong><p>{snapshot.publisher.baseUrl}</p><small>{snapshot.publisher.publicModels.join("、")}</small></div></article> : <p className="empty-state">Composer 编译通过后即可创建本地出口。</p>}</div>; }
function Docs({ document, language, onLanguage, published }: { document: LiveDocument | null; language: TemplateLanguage; onLanguage: (value: TemplateLanguage) => void; published: boolean }) { return <div className="canvas-list-page">{published ? <LiveDocumentation document={document} language={language} loading onLanguage={onLanguage} /> : <p className="empty-state">配置并发布编组方案出口后，将根据 Composer 服务计划生成完整文档。</p>}</div>; }
function Runs({ records }: { records: ExecutionTrace[] }) { return <div className="canvas-list-page"><div className="section-heading"><div><p className="eyebrow">COMPOSITION AUDIT</p><h2>运行记录</h2></div><Badge color="secondary" variant="soft">{records.length} 条</Badge></div>{records.length ? records.map((record) => <article className="canvas-run-card" key={record.correlation_id}><History /><div><strong>{record.public_model}</strong><small>{record.total_latency_ms} ms · {record.streaming ? "流式" : "非流式"} · {record.result}</small></div></article>) : <p className="empty-state">此编组方案尚无调用记录。</p>}</div>; }
function RuntimeReportPanel({ report, onOpenWorkflow }: { report: RuntimeValidationReport; onOpenWorkflow: () => void }) {
  const issueCount = report.errors.length + report.warnings.length + report.missingSecrets.length + report.unreachableNodes.length;
  if (!issueCount && report.valid) {
    return <div className="canvas-runtime-report ok" role="status"><Badge color="success" variant="soft">运行校验通过</Badge><span>{report.candidateCount} 个候选 · {report.publicModels.length || 1} 个公开模型 · {report.selectedStrategy}</span></div>;
  }
  const issue = report.errors[0]?.message ?? report.warnings[0]?.message ?? report.missingSecrets[0] ?? report.unreachableNodes[0] ?? "需要检查编排语义";
  return <div className="canvas-runtime-report attention" role={report.errors.length ? "alert" : "status"}><div><Badge color={report.errors.length ? "danger" : "warning"} variant="soft">{report.errors.length ? "存在阻塞项" : "存在警告"}</Badge><span>{issue}</span></div><Button color="secondary" variant="soft" size="sm" onClick={onOpenWorkflow}>定位到编排</Button></div>;
}
function lifecycleLabel(value: string) { return ({ running: "运行中", paused: "已暂停", failed: "失败", stopped: "已停止", draft: "未发布" } as Record<string, string>)[value] ?? value; }
function isDesktopSnapshot(value: unknown): value is DesktopSnapshot { return Boolean(value && typeof value === "object" && "initialized" in value); }
